apiVersion: v1
kind: Service
metadata:
  namespace: todo
  name: todo-view
  labels:
    todo-app-service: todo-view
spec:
  type: ClusterIP
  selector:
    todo-app-pod: todo-view
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8090

